blog_app/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post, name='post'),
    path('<int:id>/', views.post_detail, name='post_detail'),
]

my_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio_app.urls')),
    path('blog/', include('blog_app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio_app/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='home'),
]

blog_app/models.py
from django.db import models
import datetime

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='blog/images/')
    date = models.DateField(datetime.date.today)

    def __str__(self):
        return self.title

    def delete(self, using=None, keep_parents=False):
        self.image.storage.delete(self.image.name)
        super().delete()

portfolio_app/models.py
from django.db import models


class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=255)
    image = models.ImageField(upload_to='images/')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

    def delete(self, using=None, keep_parents=False):
        self.image.storage.delete(self.image.name)
        super().delete()

blog_app/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post

# Create your views here.
def post(request):
    posts = Post.objects.all()
    return render(request, 'post.html', {'posts': posts})


def post_detail(request, id):
    posts = get_object_or_404(Post, pk=id)
    return render(request, 'post_detail.html', {'posts': posts})

portfolio_app/views.py
from django.shortcuts import render
from .models import Project

# Create your views here.
def home(request):
    projects = Project.objects.order_by('id')
    return render(request, 'home.html', {'projects': projects})

blog_app/templates/post.html
{% extends 'layout.html' %}

{% block content %}

<h1 class="text-center">Posts</h1>


{% for post in posts %}

<div class="p-3">
    <div class="card card-body bg-black">
        <div class="row">

            <div class="col-3">
                <img src="{{ post.image.url }}" alt="{{post.title}}" class="img-fluid">
            </div>

            <div class="col-9">
                <h3>{{ post.title }}</h3>
                <p>{{ post.description|truncatechars:100 }}</p>

                <a href="{% url 'blog:post_detail' post.id %}" class="btn btn-primary">{{ post.title }}</a>
            </div>

        </div>

    </div>
</div>

{% endfor %}

{% endblock %}

blog_app/templates/post_detail.html
{% extends 'layout.html' %}

{% block content %}

<div class="text-center">
    <h2>{{posts.title}}</h2>
<h4 class="my-2 h5 text-muted">{{posts.date|date:'M d Y'}}</h4>

<img src="{{posts.image.url}}" alt="{{post.title}}" class="img-fluid">

<div class="my-4">
    <p>{{posts.description}}</p>
</div>
</div>

{% endblock %}

portfolio_app/templates/home.html
{% extends 'layout.html'  %}

{% block content %}

{% load static %}

<header class="row bg-black">
    <div class="col-md-4">
        <img src="{% static 'portfolio/foto_perfil.jpg' %}" width="320">
    </div>

    <div class="col-md-8 my-auto">
        <h1>Mi nombre es <strong>Wilson De Caro</strong></h1>
        <h3>Soy Python | Back-end Developer jr.</h3>
        <p>Soy una persona. Bueno yo me considero como alguien que le gusta tomar nuevos retos cada día, me gusta ser
        proactivo, organizativo, comunicativo y adquisitivo de nuevos conocimientos. Soy un programador jr. Que está buscando
        colaborar o iniciarse como Back-end Developer Python | Django de manera profesional, brindando mis conocimientos,
        habilidades y así, seguir avanzar. Tengo conocimientos de tecnologías como Python, Django, SQL|PostgreSQL. </p>
        <a href="{% static 'portfolio/cv_wilson.pdf' %}" class="btn btn-primary btn-lg rounded-0 my-3">Descargar CV</a>
    </div>
</header>

<br/>
<div class="row my-64 text-center">

    <h3>Mis Poryectos</h3>

    {% for project in projects %}

    <div class="col-md-4 p-4">
        <div class="card bg-black card-project">
            <div class="card-body">
                <h2>{{ project.title }}</h2>
                <img src="{{ project.image.url }}" alt="{{project.title}}" class="card-img-top"/>
                <p>{{ project.description }}</p>
                <a href="{{ project.url }}" class="btn btn-light rounded-0 btn-sm" target="_blank">{{ project.title }}</a>
            </div>
        </div>
    </div>

    {% endfor %}
</div>


{% endblock %}

portfolio_app/templates/layout.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Portfolio Django</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main.css' %}">

</head>
<body class="text-light">

{% include 'nav/navbar.html' %}

    <div class="container p-4">
        {% block content %}
        {% endblock %}
    </div>

</body>
</html>

portfolio_app/templates/nav/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark"
     style="background: linear-gradient(90deg, rgba(88,11,65,1) 14%, rgba(0,0,0,1) 100%);"> <!--bg-dark-->
  <div class="container">
    <a class="navbar-brand fw-bold fst-italic" href="/">WADECAP</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:post' %}">Blog</a>
        </li>
        <li class="nav-item d-flex align-items-center">
          <a class="btn btn-primary btn-sm" href="{% static 'portfolio/cv_wilson.pdf' %}" target="_blank">
            Descargar CV</a>
        </li>
      </ul>
    </div>
  </div>
</nav>